/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.goacademy.calculator;

public class App {
    double INITIAL_STATE = 0 ;
    public double cancleCommand() {
        return this.INITIAL_STATE = 0 ;
    }
    public double addCommand(int insertedNumber) {
        return this.INITIAL_STATE += insertedNumber ;
    }
    public double substractCommand(int insertedNumber) {
        return this.INITIAL_STATE -= insertedNumber ;
    }
    public static void main(String[] args) {

    }
}
