/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.goacademy.calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest = new App();
    @Test public void givenCalculatorShouldReturnZeroInitialNumber() {
        assertEquals(0.01, classUnderTest.cancleCommand(), 0.01);
    }
    @Test public void givenCalculatorAddNumberShouldReturnNumber() {
        assertEquals(2.01, classUnderTest.addCommand(2), 0.01);
    }
    @Test public void givenCalculatorSusbtractNumberShouldReturnNumber() {
        assertEquals(-2.01, classUnderTest.substractCommand(2), 0.01);
    }
    @Test public void givenCalculatorMultiplyNumberShouldReturnNumber() {
        assertEquals(0.01, classUnderTest.multiplyCommand(1), 0.01);
    }
    @Test public void givenCalculatorDivideNumberShouldReturnNumber() {
        classUnderTest.INITIAL_STATE = 4;
        assertEquals(2.01, classUnderTest.divideCommand(2), 0.01);
    }
    @Test public void givenCalculatorDivideZeroNumberShouldReturnZero() {
        assertEquals(0.01, classUnderTest.divideCommand(0), 0.01);
    }
}
