/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.goacademy.calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest = new App();
    @Test public void givenCalculatorShouldReturnZeroInitialNumber() {
        assertEquals(0.01, classUnderTest.cancleCommand(), 0.01);
    }
}
